org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.workers.max=4
kotlin.compiler.execution.strategy=in-process
googleServices.missing.passthrough=true
android.builtInKotlin=false
android.newDsl=false
ksp.incremental=false
android.dependencyResolutionManagement.withProjectDependencies=true
# AndroidX Settings
android.useAndroidX=true
android.enableJetifier=true
